services:
  proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    healthcheck:
      test: [ "CMD", "service", "nginx", "status" ]
      interval: 10s
      timeout: 5s
      retries: 5

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    environment:
      - DEFAULT_EMAIL=laurin@kerk-loh.de
    volumes_from:
      - proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy

  homeassistant:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    restart: unless-stopped
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    ports:
      - "8123:8123"
    environment:
      LETSENCRYPT_HOST: assistant.home.kerkloh.com
      VIRTUAL_HOST: assistant.home.kerkloh.com
      VIRTUAL_PORT: 8123

  mqtt:
    image: eclipse-mosquitto
    restart: unless-stopped
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    ports:
      - 1883:1883
      - 9001:9001

  zigbee2mqtt:
    image: koenkk/zigbee2mqtt
    restart: unless-stopped
    volumes:
      - ./zigbee2mqtt/data:/app/data
      - /run/udev:/run/udev:ro
    expose:
      - 8080
    environment:
      TZ: Europe/Berlin
      VIRTUAL_HOST: z2m.home.kerkloh.com
      VIRTURAL_PORT: 8080
    devices:
      - /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_DE2471574-if00:/dev/ttyUSB0

  p2g-laurin-api:
    image: philosowaffle/peloton-to-garmin:api-stable
    user: :p2g
    environment:
      - TZ=Europe/Berlin
      - P2G_CONFIG_DIRECTORY=/app/config
    volumes:
      - ./p2g/laurin/config/api/:/app/config
      - p2g-laurin-data:/app/data # recommended for saving settings across restarts
      - p2g-laurin-output:/app/output # optional, if you want access to the generated workout and log files

  p2g-laurin-webui:
    image: philosowaffle/peloton-to-garmin:webui-stable
    user: :p2g
    expose:
      - 8080
    environment:
      TZ: America/Chicago
      P2G_CONFIG_DIRECTORY: /app/config
      VIRTUAL_HOST: p2glaurin.home.kerkloh.com
      VIRTURAL_PORT: 8080
    volumes:
      - ./p2g/laurin/config/webui:/app/config
    depends_on:
      - p2g-laurin-api

  p2g-linh-api:
    image: philosowaffle/peloton-to-garmin:api-stable
    user: :p2g
    environment:
      - TZ=Europe/Berlin
      - P2G_CONFIG_DIRECTORY=/app/config
    volumes:
      - ./p2g/linh/config/api/:/app/config
      - p2g-linh-data:/app/data # recommended for saving settings across restarts
      - p2g-linh-output:/app/output # optional, if you want access to the generated workout and log files

  p2g-linh-webui:
    image: philosowaffle/peloton-to-garmin:webui-stable
    user: :p2g
    expose:
      - 8080
    environment:
      TZ: America/Chicago
      P2G_CONFIG_DIRECTORY: /app/config
      VIRTUAL_HOST: p2glinh.home.kerkloh.com
      VIRTURAL_PORT: 8080
    volumes:
      - ./p2g/linh/config/webui:/app/config
    depends_on:
      - p2g-linh-api

volumes:
  mosquitto-data:
  mosquitto-log:
  certs:
  vhost:
  html:
  acme:
  p2g-laurin-data:
  p2g-laurin-output:
  p2g-linh-data:
  p2g-linh-output:


networks:
  default:
