- id: '1707411011751'
  alias: styrbar logger
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.0x003c84fffe266d21_action
    not_to:
  action:
  - variables:
      command: '{{ trigger.to_state.state }}'
  - service: system_log.write
    data:
      message: 'Syrbar command: {{ command }}'
  mode: parallel
- id: '1707432559743'
  alias: z2m - IKEA STYRBAR
  description: ''
  use_blueprint:
    path: custom/styrbar.yaml
    input:
      remote: sensor.0x003c84fffe266d21_action
      button_on:
      - service: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: 693beed6b4206eb1c63c1d67965d4ad4
      button_off:
      - service: light.turn_off
        metadata: {}
        data: {}
        target:
          device_id: 693beed6b4206eb1c63c1d67965d4ad4
      button_brightness_move_up:
      - service: light.turn_on
        metadata: {}
        data:
          brightness_step_pct: 4
        target:
          device_id: 693beed6b4206eb1c63c1d67965d4ad4
      button_brightness_move_down:
      - service: light.turn_on
        target:
          device_id: 693beed6b4206eb1c63c1d67965d4ad4
        data:
          brightness_step_pct: -5
- id: '1708373485606'
  alias: Linh left work
  description: ''
  trigger:
  - platform: zone
    entity_id: person.linh
    zone: zone.arbeit
    event: leave
  condition: []
  action:
  - device_id: 23e32aee7e0e07213931b1b54e315f78
    domain: mobile_app
    type: notify
    message: Linh left work
  mode: single
- id: '1711199527347'
  alias: laurin home
  description: ''
  trigger:
  - platform: zone
    entity_id: person.laurin
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: d1c6a89a73c809a46fecd4ec532f6c22
    domain: mobile_app
    type: notify
    message: Laurin ist Zuhause angekommen ❤️
  mode: single
